CREATE OR REPLACE TABLE SCRATCH.BASIS.PROPERTY_POI_DISTANCES AS
WITH property_coords AS (
  SELECT DISTINCT
    b.CC_LIST_ID,
    b.CC_PROPERTY_ID,
    m.PROPERTY_LATITUDE,
    m.PROPERTY_LONGITUDE,
    MOD(ABS(HASH(b.CC_PROPERTY_ID)), 10) AS partition_key
  FROM SCRATCH.BASIS.STG_MLS b
  INNER JOIN ROC_MLS_DATA.ATTOM.MLS m
    ON b.CC_PROPERTY_ID = m.CC_PROPERTY_ID
  WHERE b.CC_PROPERTY_ID IS NOT NULL
    AND m.PROPERTY_LATITUDE IS NOT NULL
    AND m.PROPERTY_LONGITUDE IS NOT NULL
    AND LOWER(m.STATE) = 'nc'
)
SELECT
  p.CC_PROPERTY_ID,
  p.CC_LIST_ID,
  poi.AMENITY_TYPE,
  SQRT(
    POWER((p.PROPERTY_LATITUDE - poi.LATITUDE) * 69, 2) +
    POWER((p.PROPERTY_LONGITUDE - poi.LONGITUDE) * 54.6, 2)
  ) AS distance_miles
FROM property_coords p
INNER JOIN SCRATCH.PUBLIC.NORTH_CAROLINA_POI_RAW poi
  ON poi.LATITUDE BETWEEN p.PROPERTY_LATITUDE - 0.09 AND p.PROPERTY_LATITUDE + 0.09
  AND poi.LONGITUDE BETWEEN p.PROPERTY_LONGITUDE - 0.09 AND p.PROPERTY_LONGITUDE + 0.09
WHERE
  SQRT(
    POWER((p.PROPERTY_LATITUDE - poi.LATITUDE) * 69, 2) +
    POWER((p.PROPERTY_LONGITUDE - poi.LONGITUDE) * 54.6, 2)
  ) <= 5.0
;